### ISSUE TITLE
Override of mail subject or body cuts off after first word

### ISSUE THREAD

**Issue by bwachter** [aardsoft/cups-email#3]
The recently introduced override option for subject and mail text runs into problems with the splitting of cups provided options, resulting in splitting of the string during option parsing.

**Comment by greigm** [comment]
Has there been any progress on this? I'm trying to google "how does CUPS split printing options" and all sorts of variants with "spaces" and it's proving a futile mission. I'm struggling to understand how the default can contain spaces just fine but this can't seem to be passed to it on the commandline. I'm looking for other similar CUPS models that have spaces to see how they've done this, but that's a tricky google also! I've tried escaping with shell escapes, unicode, html entities(!!!), and setting subject as a bash array, and as an escaped printf. Nothing seems to work. I'd love to help but I can't find what I need to educate myself to the point where I can.

**Comment by bwachter** [comment]
Not really - overriding those two things are a nice to have new feature for me, so wasn't putting much effort in. I added a debug statement in d59bf5fc08e1156f6b6f267b75b632fbc72dd4df to help figuring out at which point the options get broken up, but I don't remember if I continued debugging after this.

So first step would be figuring out if the script does something stupid, or if cups already does something stupid before passing it to us. My guess is that it might be [line 119](https://github.com/aardsoft/cups-email/blob/master/email#L119) needing different IFS settings.

**Comment by greigm** [comment]
Ah, I didn't see the quite clearly commented bug! Sorry to waste your time. I'll have a look at it when I have a moment, maybe fresh eyes can help! 😁 Thanks for the response!

**Comment by greigm** [comment]
Oh, it's most definitely CUPS. eg.
lp -d EMAIL -o MailTo=Custom.greig@example.com '-o MailSubject=Custom.Testing Spaces' -o MailFrom=Custom.greig@example.com test.txt

D [12/Dec/2023:07:15:47 +1300] [Job 35] Options - finishings=3 MailFrom=Custom.greig@example.com MailSubject=Custom.Testing MailTo=Custom.greig@example.com number-up=1 print-color-mode=color Spaces job-uuid=urn:uuid:bb013859-55d1-31e7-4296-666c7bd694b9 job-originating-host-name=localhost date-time-at-creation= date-time-at-processing= time-at-creation=1702318547 time-at-processing=1702318547 document-name-supplied=test.txt

Weirdly, not only is it not handling them properly, it's inserting other options inside the quoted string with the space!

I can't find any mention of this bug anywhere, and yet it seems 100% reproducible even with a simple backend filter that just dumps to a text file. Bizzarre. I guess it's not going to get fixed by my pitiful code skills any time soon!

**Comment by bwachter** [comment]
It seems you have one typo in the documentation, otherwise this looks like a sensible workaround - thanks. I assume you've tested it properly, so with the typo fixed I can merge that.

Cups documentation is generally horrible - I spent a lot of time digging through the cups sources to get a rough idea how it expects to do things for the initial version of this script, and even that is not that useful as it's a rather convoluted mess, and you can have filters and even the frontend doing additional stupid things you didn't expect. You can see that in the MailToSource handling - that ballooned to the current state just to make sure that every cups frontend I had available is capable of specifying the mail address in some form.

**Comment by greigm** [comment]
All fixed. It's tested, and in production but only on two different flavours of Ubuntu - 20.04 and 22.04.

Agree 100% on the CUPS docs!

**Comment by bwachter** [comment]
Looks good, I've merged it now. Thank you!
